/** Original Komorebi residents, shared by the scene and profiles. */
export const cats = [
  {
    name: "きなこ",
    en: "Kinako",
    color: "#c88e53",
    coat: "茶トラ",
    personality: "好奇心いっぱいの甘えんぼ",
    mood: "おさんぽ中",
    body: 0xd6a06b,
    patch: 0x9e6038,
  },
  {
    name: "もち",
    en: "Mochi",
    color: "#ddd9cd",
    coat: "しろねこ",
    personality: "のんびり、マイペース",
    mood: "ひなたぼっこ",
    body: 0xf4eee0,
    patch: 0xe6dbc6,
  },
  {
    name: "くろ",
    en: "Kuro",
    color: "#565652",
    coat: "くろねこ",
    personality: "クールに見えて、実はさみしがり",
    mood: "おさんぽ中",
    body: 0x484b48,
    patch: 0x333634,
  },
  {
    name: "みけ",
    en: "Mike",
    color: "#ba805c",
    coat: "三毛猫",
    personality: "カフェの小さな冒険家",
    mood: "きょろきょろ",
    body: 0xf0e4cd,
    patch: 0xa85f36,
  },
  {
    name: "ごま",
    en: "Goma",
    color: "#989c99",
    coat: "サバトラ",
    personality: "おもちゃには目がない",
    mood: "おさんぽ中",
    body: 0x969c99,
    patch: 0x606966,
  },
  {
    name: "ちゃい",
    en: "Chai",
    color: "#c8a787",
    coat: "シャム",
    personality: "お昼寝とおやつが大好き",
    mood: "おひるね",
    body: 0xd7bb94,
    patch: 0x6b5142,
  },
];
export const favorites = [
  "羽のおもちゃと、窓辺の特等席",
  "やわらかなクッションと、静かな午後",
  "そっと隣に座ってくれる人",
  "高いところと、新しい発見",
  "ころころ転がるボール",
  "おいしいおやつと、長いお昼寝",
];
export const stories = [
  "はじめましてでも、すぐに足元へ。小さな探検が終わると、そばで甘えたくなるようです。",
  "急がず、騒がず、気の向くまま。ひなたを見つけるのが、誰よりも上手な子です。",
  "最初は少し離れて、あなたを観察。ほどよい距離で待っていると、そっと心を開いてくれます。",
  "いつものカフェにも、発見がいっぱい。今日も好奇心に導かれて、あちこち歩き回ります。",
  "おもちゃの気配に、お耳がぴん。遊んだあとは、お気に入りの場所でひと休み。",
  "あたたかい場所で、うとうと。おやつの時間だけは、ちゃんと覚えている食いしんぼうです。",
];
